name: CD

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    name: Deploy prod
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    concurrency:
      group: deploy-prod
      cancel-in-progress: false
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      DATABRICKS_SP_CLIENT_ID: ${{ secrets.DATABRICKS_SP_CLIENT_ID }}
      CATALOG: ${{ vars.CATALOG || 'dataops_template' }}
    steps:
      - uses: actions/checkout@v6

      - name: Fix detached HEAD
        run: git checkout -B ${{ github.ref_name }}

      - uses: databricks/setup-cli@main

      - uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync

      - name: Deploy prod
        run: make deploy-prod

      - name: Upload sample data
        run: make upload-sample-data-prod

      - name: Run operational job
        run: make run-prod
